# Generated by Django 4.2.1 on 2023-07-03 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stars",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
